#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacjaSzkoleniowa
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="szkolenia")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcountries(countries instance);
    partial void Updatecountries(countries instance);
    partial void Deletecountries(countries instance);
    partial void Insertusers(users instance);
    partial void Updateusers(users instance);
    partial void Deleteusers(users instance);
    partial void Insertcurrency(currency instance);
    partial void Updatecurrency(currency instance);
    partial void Deletecurrency(currency instance);
    partial void Inserteducation(education instance);
    partial void Updateeducation(education instance);
    partial void Deleteeducation(education instance);
    partial void Insertoffers(offers instance);
    partial void Updateoffers(offers instance);
    partial void Deleteoffers(offers instance);
    partial void Insertparticipants(participants instance);
    partial void Updateparticipants(participants instance);
    partial void Deleteparticipants(participants instance);
    partial void Insertparticipants_trainings(participants_trainings instance);
    partial void Updateparticipants_trainings(participants_trainings instance);
    partial void Deleteparticipants_trainings(participants_trainings instance);
    partial void Inserttrainings(trainings instance);
    partial void Updatetrainings(trainings instance);
    partial void Deletetrainings(trainings instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::AplikacjaSzkoleniowa.Properties.Settings.Default.szkoleniaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<countries> countries
		{
			get
			{
				return this.GetTable<countries>();
			}
		}
		
		public System.Data.Linq.Table<users> users
		{
			get
			{
				return this.GetTable<users>();
			}
		}
		
		public System.Data.Linq.Table<currency> currency
		{
			get
			{
				return this.GetTable<currency>();
			}
		}
		
		public System.Data.Linq.Table<education> education
		{
			get
			{
				return this.GetTable<education>();
			}
		}
		
		public System.Data.Linq.Table<offers> offers
		{
			get
			{
				return this.GetTable<offers>();
			}
		}
		
		public System.Data.Linq.Table<participants> participants
		{
			get
			{
				return this.GetTable<participants>();
			}
		}
		
		public System.Data.Linq.Table<participants_trainings> participants_trainings
		{
			get
			{
				return this.GetTable<participants_trainings>();
			}
		}
		
		public System.Data.Linq.Table<trainings> trainings
		{
			get
			{
				return this.GetTable<trainings>();
			}
		}
		
		public System.Data.Linq.Table<view_participants_trainings> view_participants_trainings
		{
			get
			{
				return this.GetTable<view_participants_trainings>();
			}
		}
		
		public System.Data.Linq.Table<view_participants> view_participants
		{
			get
			{
				return this.GetTable<view_participants>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.countries")]
	public partial class countries : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id_countries;
		
		private string _code;
		
		private string _continent_code;
		
		private string _name;
		
		private string _full_name;
		
		private EntitySet<participants> _participants;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_countriesChanging(decimal value);
    partial void Onid_countriesChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void Oncontinent_codeChanging(string value);
    partial void Oncontinent_codeChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onfull_nameChanging(string value);
    partial void Onfull_nameChanged();
    #endregion
		
		public countries()
		{
			this._participants = new EntitySet<participants>(new Action<participants>(this.attach_participants), new Action<participants>(this.detach_participants));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_countries", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id_countries
		{
			get
			{
				return this._id_countries;
			}
			set
			{
				if ((this._id_countries != value))
				{
					this.Onid_countriesChanging(value);
					this.SendPropertyChanging();
					this._id_countries = value;
					this.SendPropertyChanged("id_countries");
					this.Onid_countriesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_continent_code", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string continent_code
		{
			get
			{
				return this._continent_code;
			}
			set
			{
				if ((this._continent_code != value))
				{
					this.Oncontinent_codeChanging(value);
					this.SendPropertyChanging();
					this._continent_code = value;
					this.SendPropertyChanged("continent_code");
					this.Oncontinent_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_full_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string full_name
		{
			get
			{
				return this._full_name;
			}
			set
			{
				if ((this._full_name != value))
				{
					this.Onfull_nameChanging(value);
					this.SendPropertyChanging();
					this._full_name = value;
					this.SendPropertyChanged("full_name");
					this.Onfull_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="countries_participants", Storage="_participants", ThisKey="id_countries", OtherKey="id_countries")]
		public EntitySet<participants> participants
		{
			get
			{
				return this._participants;
			}
			set
			{
				this._participants.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_participants(participants entity)
		{
			this.SendPropertyChanging();
			entity.countries = this;
		}
		
		private void detach_participants(participants entity)
		{
			this.SendPropertyChanging();
			entity.countries = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users")]
	public partial class users : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id_users;
		
		private string _login;
		
		private string _password;
		
		private System.Nullable<bool> _active;
		
		private System.Nullable<System.DateTime> _date_add;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_usersChanging(decimal value);
    partial void Onid_usersChanged();
    partial void OnloginChanging(string value);
    partial void OnloginChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnactiveChanging(System.Nullable<bool> value);
    partial void OnactiveChanged();
    partial void Ondate_addChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_addChanged();
    #endregion
		
		public users()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_users", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id_users
		{
			get
			{
				return this._id_users;
			}
			set
			{
				if ((this._id_users != value))
				{
					this.Onid_usersChanging(value);
					this.SendPropertyChanging();
					this._id_users = value;
					this.SendPropertyChanged("id_users");
					this.Onid_usersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="VarChar(50)")]
		public string login
		{
			get
			{
				return this._login;
			}
			set
			{
				if ((this._login != value))
				{
					this.OnloginChanging(value);
					this.SendPropertyChanging();
					this._login = value;
					this.SendPropertyChanged("login");
					this.OnloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(250)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_add", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_add
		{
			get
			{
				return this._date_add;
			}
			set
			{
				if ((this._date_add != value))
				{
					this.Ondate_addChanging(value);
					this.SendPropertyChanging();
					this._date_add = value;
					this.SendPropertyChanged("date_add");
					this.Ondate_addChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.currency")]
	public partial class currency : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id_currency;
		
		private string _code;
		
		private string _name;
		
		private EntitySet<trainings> _trainings;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_currencyChanging(decimal value);
    partial void Onid_currencyChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public currency()
		{
			this._trainings = new EntitySet<trainings>(new Action<trainings>(this.attach_trainings), new Action<trainings>(this.detach_trainings));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_currency", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id_currency
		{
			get
			{
				return this._id_currency;
			}
			set
			{
				if ((this._id_currency != value))
				{
					this.Onid_currencyChanging(value);
					this.SendPropertyChanging();
					this._id_currency = value;
					this.SendPropertyChanged("id_currency");
					this.Onid_currencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(3)")]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="currency_trainings", Storage="_trainings", ThisKey="id_currency", OtherKey="id_currency")]
		public EntitySet<trainings> trainings
		{
			get
			{
				return this._trainings;
			}
			set
			{
				this._trainings.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_trainings(trainings entity)
		{
			this.SendPropertyChanging();
			entity.currency = this;
		}
		
		private void detach_trainings(trainings entity)
		{
			this.SendPropertyChanging();
			entity.currency = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.education")]
	public partial class education : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id_education;
		
		private string _name;
		
		private EntitySet<participants> _participants;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_educationChanging(decimal value);
    partial void Onid_educationChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public education()
		{
			this._participants = new EntitySet<participants>(new Action<participants>(this.attach_participants), new Action<participants>(this.detach_participants));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_education", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id_education
		{
			get
			{
				return this._id_education;
			}
			set
			{
				if ((this._id_education != value))
				{
					this.Onid_educationChanging(value);
					this.SendPropertyChanging();
					this._id_education = value;
					this.SendPropertyChanged("id_education");
					this.Onid_educationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="education_participants", Storage="_participants", ThisKey="id_education", OtherKey="id_education")]
		public EntitySet<participants> participants
		{
			get
			{
				return this._participants;
			}
			set
			{
				this._participants.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_participants(participants entity)
		{
			this.SendPropertyChanging();
			entity.education = this;
		}
		
		private void detach_participants(participants entity)
		{
			this.SendPropertyChanging();
			entity.education = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.offers")]
	public partial class offers : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id_offers;
		
		private string _name;
		
		private System.Nullable<bool> _active;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_offersChanging(decimal value);
    partial void Onid_offersChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnactiveChanging(System.Nullable<bool> value);
    partial void OnactiveChanged();
    #endregion
		
		public offers()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_offers", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id_offers
		{
			get
			{
				return this._id_offers;
			}
			set
			{
				if ((this._id_offers != value))
				{
					this.Onid_offersChanging(value);
					this.SendPropertyChanging();
					this._id_offers = value;
					this.SendPropertyChanged("id_offers");
					this.Onid_offersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.participants")]
	public partial class participants : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id_participants;
		
		private string _name;
		
		private string _surname;
		
		private string _email;
		
		private string _phone;
		
		private System.Nullable<decimal> _id_countries;
		
		private string _city;
		
		private string _street;
		
		private string _postal_code;
		
		private System.Nullable<decimal> _id_offers;
		
		private System.Nullable<decimal> _id_education;
		
		private EntitySet<participants_trainings> _participants_trainings;
		
		private EntityRef<countries> _countries;
		
		private EntityRef<education> _education;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_participantsChanging(decimal value);
    partial void Onid_participantsChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnsurnameChanging(string value);
    partial void OnsurnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void Onid_countriesChanging(System.Nullable<decimal> value);
    partial void Onid_countriesChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnstreetChanging(string value);
    partial void OnstreetChanged();
    partial void Onpostal_codeChanging(string value);
    partial void Onpostal_codeChanged();
    partial void Onid_offersChanging(System.Nullable<decimal> value);
    partial void Onid_offersChanged();
    partial void Onid_educationChanging(System.Nullable<decimal> value);
    partial void Onid_educationChanged();
    #endregion
		
		public participants()
		{
			this._participants_trainings = new EntitySet<participants_trainings>(new Action<participants_trainings>(this.attach_participants_trainings), new Action<participants_trainings>(this.detach_participants_trainings));
			this._countries = default(EntityRef<countries>);
			this._education = default(EntityRef<education>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_participants", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id_participants
		{
			get
			{
				return this._id_participants;
			}
			set
			{
				if ((this._id_participants != value))
				{
					this.Onid_participantsChanging(value);
					this.SendPropertyChanging();
					this._id_participants = value;
					this.SendPropertyChanged("id_participants");
					this.Onid_participantsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_surname", DbType="VarChar(50)")]
		public string surname
		{
			get
			{
				return this._surname;
			}
			set
			{
				if ((this._surname != value))
				{
					this.OnsurnameChanging(value);
					this.SendPropertyChanging();
					this._surname = value;
					this.SendPropertyChanged("surname");
					this.OnsurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(150)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NChar(10)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_countries", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> id_countries
		{
			get
			{
				return this._id_countries;
			}
			set
			{
				if ((this._id_countries != value))
				{
					if (this._countries.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_countriesChanging(value);
					this.SendPropertyChanging();
					this._id_countries = value;
					this.SendPropertyChanged("id_countries");
					this.Onid_countriesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(20)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_street", DbType="VarChar(20)")]
		public string street
		{
			get
			{
				return this._street;
			}
			set
			{
				if ((this._street != value))
				{
					this.OnstreetChanging(value);
					this.SendPropertyChanging();
					this._street = value;
					this.SendPropertyChanged("street");
					this.OnstreetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postal_code", DbType="VarChar(5)")]
		public string postal_code
		{
			get
			{
				return this._postal_code;
			}
			set
			{
				if ((this._postal_code != value))
				{
					this.Onpostal_codeChanging(value);
					this.SendPropertyChanging();
					this._postal_code = value;
					this.SendPropertyChanged("postal_code");
					this.Onpostal_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_offers", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> id_offers
		{
			get
			{
				return this._id_offers;
			}
			set
			{
				if ((this._id_offers != value))
				{
					this.Onid_offersChanging(value);
					this.SendPropertyChanging();
					this._id_offers = value;
					this.SendPropertyChanged("id_offers");
					this.Onid_offersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_education", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> id_education
		{
			get
			{
				return this._id_education;
			}
			set
			{
				if ((this._id_education != value))
				{
					if (this._education.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_educationChanging(value);
					this.SendPropertyChanging();
					this._id_education = value;
					this.SendPropertyChanged("id_education");
					this.Onid_educationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="participants_participants_trainings", Storage="_participants_trainings", ThisKey="id_participants", OtherKey="id_participants")]
		public EntitySet<participants_trainings> participants_trainings
		{
			get
			{
				return this._participants_trainings;
			}
			set
			{
				this._participants_trainings.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="countries_participants", Storage="_countries", ThisKey="id_countries", OtherKey="id_countries", IsForeignKey=true)]
		public countries countries
		{
			get
			{
				return this._countries.Entity;
			}
			set
			{
				countries previousValue = this._countries.Entity;
				if (((previousValue != value) 
							|| (this._countries.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._countries.Entity = null;
						previousValue.participants.Remove(this);
					}
					this._countries.Entity = value;
					if ((value != null))
					{
						value.participants.Add(this);
						this._id_countries = value.id_countries;
					}
					else
					{
						this._id_countries = default(Nullable<decimal>);
					}
					this.SendPropertyChanged("countries");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="education_participants", Storage="_education", ThisKey="id_education", OtherKey="id_education", IsForeignKey=true)]
		public education education
		{
			get
			{
				return this._education.Entity;
			}
			set
			{
				education previousValue = this._education.Entity;
				if (((previousValue != value) 
							|| (this._education.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._education.Entity = null;
						previousValue.participants.Remove(this);
					}
					this._education.Entity = value;
					if ((value != null))
					{
						value.participants.Add(this);
						this._id_education = value.id_education;
					}
					else
					{
						this._id_education = default(Nullable<decimal>);
					}
					this.SendPropertyChanged("education");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_participants_trainings(participants_trainings entity)
		{
			this.SendPropertyChanging();
			entity.participants = this;
		}
		
		private void detach_participants_trainings(participants_trainings entity)
		{
			this.SendPropertyChanging();
			entity.participants = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.participants_trainings")]
	public partial class participants_trainings : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id_participants_trainings;
		
		private System.Nullable<decimal> _id_participants;
		
		private System.Nullable<decimal> _id_trainings;
		
		private EntityRef<participants> _participants;
		
		private EntityRef<trainings> _trainings;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_participants_trainingsChanging(decimal value);
    partial void Onid_participants_trainingsChanged();
    partial void Onid_participantsChanging(System.Nullable<decimal> value);
    partial void Onid_participantsChanged();
    partial void Onid_trainingsChanging(System.Nullable<decimal> value);
    partial void Onid_trainingsChanged();
    #endregion
		
		public participants_trainings()
		{
			this._participants = default(EntityRef<participants>);
			this._trainings = default(EntityRef<trainings>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_participants_trainings", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id_participants_trainings
		{
			get
			{
				return this._id_participants_trainings;
			}
			set
			{
				if ((this._id_participants_trainings != value))
				{
					this.Onid_participants_trainingsChanging(value);
					this.SendPropertyChanging();
					this._id_participants_trainings = value;
					this.SendPropertyChanged("id_participants_trainings");
					this.Onid_participants_trainingsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_participants", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> id_participants
		{
			get
			{
				return this._id_participants;
			}
			set
			{
				if ((this._id_participants != value))
				{
					if (this._participants.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_participantsChanging(value);
					this.SendPropertyChanging();
					this._id_participants = value;
					this.SendPropertyChanged("id_participants");
					this.Onid_participantsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_trainings", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> id_trainings
		{
			get
			{
				return this._id_trainings;
			}
			set
			{
				if ((this._id_trainings != value))
				{
					if (this._trainings.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_trainingsChanging(value);
					this.SendPropertyChanging();
					this._id_trainings = value;
					this.SendPropertyChanged("id_trainings");
					this.Onid_trainingsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="participants_participants_trainings", Storage="_participants", ThisKey="id_participants", OtherKey="id_participants", IsForeignKey=true)]
		public participants participants
		{
			get
			{
				return this._participants.Entity;
			}
			set
			{
				participants previousValue = this._participants.Entity;
				if (((previousValue != value) 
							|| (this._participants.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._participants.Entity = null;
						previousValue.participants_trainings.Remove(this);
					}
					this._participants.Entity = value;
					if ((value != null))
					{
						value.participants_trainings.Add(this);
						this._id_participants = value.id_participants;
					}
					else
					{
						this._id_participants = default(Nullable<decimal>);
					}
					this.SendPropertyChanged("participants");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="trainings_participants_trainings", Storage="_trainings", ThisKey="id_trainings", OtherKey="id_trainings", IsForeignKey=true)]
		public trainings trainings
		{
			get
			{
				return this._trainings.Entity;
			}
			set
			{
				trainings previousValue = this._trainings.Entity;
				if (((previousValue != value) 
							|| (this._trainings.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._trainings.Entity = null;
						previousValue.participants_trainings.Remove(this);
					}
					this._trainings.Entity = value;
					if ((value != null))
					{
						value.participants_trainings.Add(this);
						this._id_trainings = value.id_trainings;
					}
					else
					{
						this._id_trainings = default(Nullable<decimal>);
					}
					this.SendPropertyChanged("trainings");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.trainings")]
	public partial class trainings : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id_trainings;
		
		private string _name;
		
		private string _business;
		
		private string _leader;
		
		private System.DateTime _start;
		
		private System.DateTime _finish;
		
		private decimal _price;
		
		private decimal _id_currency;
		
		private string _description;
		
		private decimal _slot;
		
		private bool _active;
		
		private System.DateTime _date_add;
		
		private EntitySet<participants_trainings> _participants_trainings;
		
		private EntityRef<currency> _currency;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_trainingsChanging(decimal value);
    partial void Onid_trainingsChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnbusinessChanging(string value);
    partial void OnbusinessChanged();
    partial void OnleaderChanging(string value);
    partial void OnleaderChanged();
    partial void OnstartChanging(System.DateTime value);
    partial void OnstartChanged();
    partial void OnfinishChanging(System.DateTime value);
    partial void OnfinishChanged();
    partial void OnpriceChanging(decimal value);
    partial void OnpriceChanged();
    partial void Onid_currencyChanging(decimal value);
    partial void Onid_currencyChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnslotChanging(decimal value);
    partial void OnslotChanged();
    partial void OnactiveChanging(bool value);
    partial void OnactiveChanged();
    partial void Ondate_addChanging(System.DateTime value);
    partial void Ondate_addChanged();
    #endregion
		
		public trainings()
		{
			this._participants_trainings = new EntitySet<participants_trainings>(new Action<participants_trainings>(this.attach_participants_trainings), new Action<participants_trainings>(this.detach_participants_trainings));
			this._currency = default(EntityRef<currency>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_trainings", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id_trainings
		{
			get
			{
				return this._id_trainings;
			}
			set
			{
				if ((this._id_trainings != value))
				{
					this.Onid_trainingsChanging(value);
					this.SendPropertyChanging();
					this._id_trainings = value;
					this.SendPropertyChanged("id_trainings");
					this.Onid_trainingsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_business", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string business
		{
			get
			{
				return this._business;
			}
			set
			{
				if ((this._business != value))
				{
					this.OnbusinessChanging(value);
					this.SendPropertyChanging();
					this._business = value;
					this.SendPropertyChanged("business");
					this.OnbusinessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leader", DbType="VarChar(255)")]
		public string leader
		{
			get
			{
				return this._leader;
			}
			set
			{
				if ((this._leader != value))
				{
					this.OnleaderChanging(value);
					this.SendPropertyChanging();
					this._leader = value;
					this.SendPropertyChanged("leader");
					this.OnleaderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start", DbType="DateTime NOT NULL")]
		public System.DateTime start
		{
			get
			{
				return this._start;
			}
			set
			{
				if ((this._start != value))
				{
					this.OnstartChanging(value);
					this.SendPropertyChanging();
					this._start = value;
					this.SendPropertyChanged("start");
					this.OnstartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_finish", DbType="DateTime NOT NULL")]
		public System.DateTime finish
		{
			get
			{
				return this._finish;
			}
			set
			{
				if ((this._finish != value))
				{
					this.OnfinishChanging(value);
					this.SendPropertyChanging();
					this._finish = value;
					this.SendPropertyChanged("finish");
					this.OnfinishChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Money NOT NULL")]
		public decimal price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_currency", DbType="Decimal(18,0) NOT NULL")]
		public decimal id_currency
		{
			get
			{
				return this._id_currency;
			}
			set
			{
				if ((this._id_currency != value))
				{
					if (this._currency.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_currencyChanging(value);
					this.SendPropertyChanging();
					this._id_currency = value;
					this.SendPropertyChanged("id_currency");
					this.Onid_currencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slot", DbType="Decimal(3,0) NOT NULL")]
		public decimal slot
		{
			get
			{
				return this._slot;
			}
			set
			{
				if ((this._slot != value))
				{
					this.OnslotChanging(value);
					this.SendPropertyChanging();
					this._slot = value;
					this.SendPropertyChanged("slot");
					this.OnslotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit NOT NULL")]
		public bool active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_add", DbType="DateTime NOT NULL")]
		public System.DateTime date_add
		{
			get
			{
				return this._date_add;
			}
			set
			{
				if ((this._date_add != value))
				{
					this.Ondate_addChanging(value);
					this.SendPropertyChanging();
					this._date_add = value;
					this.SendPropertyChanged("date_add");
					this.Ondate_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="trainings_participants_trainings", Storage="_participants_trainings", ThisKey="id_trainings", OtherKey="id_trainings")]
		public EntitySet<participants_trainings> participants_trainings
		{
			get
			{
				return this._participants_trainings;
			}
			set
			{
				this._participants_trainings.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="currency_trainings", Storage="_currency", ThisKey="id_currency", OtherKey="id_currency", IsForeignKey=true)]
		public currency currency
		{
			get
			{
				return this._currency.Entity;
			}
			set
			{
				currency previousValue = this._currency.Entity;
				if (((previousValue != value) 
							|| (this._currency.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._currency.Entity = null;
						previousValue.trainings.Remove(this);
					}
					this._currency.Entity = value;
					if ((value != null))
					{
						value.trainings.Add(this);
						this._id_currency = value.id_currency;
					}
					else
					{
						this._id_currency = default(decimal);
					}
					this.SendPropertyChanged("currency");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_participants_trainings(participants_trainings entity)
		{
			this.SendPropertyChanging();
			entity.trainings = this;
		}
		
		private void detach_participants_trainings(participants_trainings entity)
		{
			this.SendPropertyChanging();
			entity.trainings = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_participants_trainings")]
	public partial class view_participants_trainings
	{
		
		private string _name_training;
		
		private System.Nullable<int> _count_save;
		
		private System.Nullable<decimal> _count_free;
		
		private decimal _slot;
		
		public view_participants_trainings()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_training", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string name_training
		{
			get
			{
				return this._name_training;
			}
			set
			{
				if ((this._name_training != value))
				{
					this._name_training = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_count_save", DbType="Int")]
		public System.Nullable<int> count_save
		{
			get
			{
				return this._count_save;
			}
			set
			{
				if ((this._count_save != value))
				{
					this._count_save = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_count_free", DbType="Decimal(11,0)")]
		public System.Nullable<decimal> count_free
		{
			get
			{
				return this._count_free;
			}
			set
			{
				if ((this._count_free != value))
				{
					this._count_free = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slot", DbType="Decimal(3,0) NOT NULL")]
		public decimal slot
		{
			get
			{
				return this._slot;
			}
			set
			{
				if ((this._slot != value))
				{
					this._slot = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_participants")]
	public partial class view_participants
	{
		
		private decimal _id_participants;
		
		private string _name;
		
		private string _surname;
		
		private string _email;
		
		private string _phone;
		
		private string _code;
		
		private string _city;
		
		private string _street;
		
		private string _postal_code;
		
		private string _education;
		
		public view_participants()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_participants", DbType="Decimal(18,0) NOT NULL")]
		public decimal id_participants
		{
			get
			{
				return this._id_participants;
			}
			set
			{
				if ((this._id_participants != value))
				{
					this._id_participants = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_surname", DbType="VarChar(50)")]
		public string surname
		{
			get
			{
				return this._surname;
			}
			set
			{
				if ((this._surname != value))
				{
					this._surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(150)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NChar(10)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this._phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this._code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(20)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this._city = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_street", DbType="VarChar(20)")]
		public string street
		{
			get
			{
				return this._street;
			}
			set
			{
				if ((this._street != value))
				{
					this._street = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postal_code", DbType="VarChar(5)")]
		public string postal_code
		{
			get
			{
				return this._postal_code;
			}
			set
			{
				if ((this._postal_code != value))
				{
					this._postal_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_education", DbType="VarChar(100)")]
		public string education
		{
			get
			{
				return this._education;
			}
			set
			{
				if ((this._education != value))
				{
					this._education = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
