<?xml version="1.0" encoding="utf-8"?><Database Name="szkolenia" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOPSZAFIRKA;Initial Catalog=szkolenia;Integrated Security=True" SettingsObjectName="AplikacjaSzkoleniowa.Properties.Settings" SettingsPropertyName="szkoleniaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.countries" Member="countries">
    <Type Name="countries">
      <Column Name="id_countries" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="continent_code" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="full_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="countries_participants" Member="participants" ThisKey="id_countries" OtherKey="id_countries" Type="participants" />
    </Type>
  </Table>
  <Table Name="dbo.users" Member="users">
    <Type Name="users">
      <Column Name="id_users" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="date_add" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.currency" Member="currency">
    <Type Name="currency">
      <Column Name="id_currency" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="currency_trainings" Member="trainings" ThisKey="id_currency" OtherKey="id_currency" Type="trainings" />
    </Type>
  </Table>
  <Table Name="dbo.education" Member="education">
    <Type Name="education">
      <Column Name="id_education" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="education_participants" Member="participants" ThisKey="id_education" OtherKey="id_education" Type="participants" />
    </Type>
  </Table>
  <Table Name="dbo.offers" Member="offers">
    <Type Name="offers">
      <Column Name="id_offers" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.participants" Member="participants">
    <Type Name="participants">
      <Column Name="id_participants" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="surname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="id_countries" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="street" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="postal_code" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="id_offers" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="id_education" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="participants_participants_trainings" Member="participants_trainings" ThisKey="id_participants" OtherKey="id_participants" Type="participants_trainings" />
      <Association Name="countries_participants" Member="countries" ThisKey="id_countries" OtherKey="id_countries" Type="countries" IsForeignKey="true" />
      <Association Name="education_participants" Member="education" ThisKey="id_education" OtherKey="id_education" Type="education" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.participants_trainings" Member="participants_trainings">
    <Type Name="participants_trainings">
      <Column Name="id_participants_trainings" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_participants" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="id_trainings" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="participants_participants_trainings" Member="participants" ThisKey="id_participants" OtherKey="id_participants" Type="participants" IsForeignKey="true" />
      <Association Name="trainings_participants_trainings" Member="trainings" ThisKey="id_trainings" OtherKey="id_trainings" Type="trainings" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.trainings" Member="trainings">
    <Type Name="trainings">
      <Column Name="id_trainings" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="business" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="leader" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="start" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="finish" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="id_currency" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="slot" Type="System.Decimal" DbType="Decimal(3,0) NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="date_add" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="trainings_participants_trainings" Member="participants_trainings" ThisKey="id_trainings" OtherKey="id_trainings" Type="participants_trainings" />
      <Association Name="currency_trainings" Member="currency" ThisKey="id_currency" OtherKey="id_currency" Type="currency" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.view_participants_trainings" Member="view_participants_trainings">
    <Type Name="view_participants_trainings">
      <Column Name="name_training" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="count_save" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="count_free" Type="System.Decimal" DbType="Decimal(11,0)" CanBeNull="true" />
      <Column Name="slot" Type="System.Decimal" DbType="Decimal(3,0) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.view_participants" Member="view_participants">
    <Type Name="view_participants">
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="surname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="code" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="city" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="street" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="postal_code" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
    </Type>
  </Table>
</Database>